export const imageAltText = 'backGroundImage'
export const profileIconAltText = 'avatarIcon'
export const editText = 'Edit profile'
export const followingText = 'Following'
export const followersText = 'Followers'
export const tweetsText = 'Tweets'
