export const resetNotifyMessage = 'Send email'
export const title = 'Edit profile'
export const profileImageAltText = 'avatar'
export const nameText = 'Name:'
export const descriptionText = 'Description:'
export const socialText = 'Social:'
export const resetText = 'Reset password'
export const editText = 'Edit'
