export const loginTitleText = 'Log in to Twitter'
export const loginButtonText = 'Log in'
export const logoAltText = 'logo'
export const signUpText = 'Sign up to Twitter'
export const passwordError = 'Enter correct password'
