export const likeIconAltText = 'likeIcon'
export const deleteText = 'Delete'
export const avatarIconAltText = 'avatarIcon'
export const imageIconAltText = 'image'
export const moreIconAltText = 'moreIcon'
