export const editText = 'Edit profile'
export const defaultDescription = 'Description...'
export const defaultSocial = '@Telegram...'
export const followingText = 'Following'
export const followersText = 'Followers'
export const successText = 'data saved successfully'
export const profileIconAltText = 'avatarIcon'
